### ISSUE TITLE
multiple multiple_text fields additional values are assigned to first instance of multiple_text field

### ISSUE THREAD

**Issue by Conzar** [ckan/ckanext-scheming#284]
If there are more than 1 multiple_text fields in a schema, additional multiple_text field values (> 1) will be assigned to the very first instance of the multiple_text field.  The first value of each additional multiple_text field are correct.  It is only when there are 2, 3, extra additional values that the problem exists.

### Example Schema

```yml
- field_name : 'multiple_text_1'
    label      : 'Multiple Text 1'
    preset     : multiple_text

  - field_name : 'multiple_text_2'
    label      : 'Multiple Text 2'
    preset     : multiple_text
```

### Example Editing

![image](https://user-images.githubusercontent.com/2646975/112088593-fd20d300-8bf4-11eb-8d7d-c34d289668f6.png)

### Example Display after edit

![image](https://user-images.githubusercontent.com/2646975/112088649-175ab100-8bf5-11eb-9c91-c88f156d8e82.png)

### Example edit after viewing the display

![image](https://user-images.githubusercontent.com/2646975/112088702-280b2700-8bf5-11eb-8846-ae7b0f186d15.png)

### JSON from action api

```json
multiple_text_1":[
         "Text 1 Text A",
         "Text 1 Text B",
         "Text 2 Text B"
      ],
      "multiple_text_2":[
         "Text 2 Text A"
      ],
```

### Summary

I have discussed on the ckan gitter with another user.  Unfortunately, neither of us know enough about how the repeating and javascript code works to provide a patch.  It was suggested to look at https://github.com/ckan/ckanext-scheming/blob/master/ckanext/scheming/assets/js/scheming-multiple-text.js
