### ISSUE TITLE
[Enhancement] Make schema available for querying

### ISSUE THREAD

**Issue by roc** [ckan/ckanext-scheming#311]
Apologies if this is well documented and I've missed it, but I would love a method for publicly querying the fields of the schema, in order to be able to produce features such as dynamic filtering by field on a front-end speaking to CKAN.

So for example `schema.yaml`

```
scheming_version: 2
dataset_type: dataset
about: Ready for production dataset schema 
about_url: http://www.example.com

dataset_fields:
  - field_name: foobar
    label: Foo bar!
    form_placeholder: Insert metasyntactic variable here!    
    required: true

  - field_name: pancake_preference
    help_text: Refer to https://en.wikipedia.org/wiki/List_of_pancakes
    label: Which Is the 
    required: true
    preset: select
    choices:
      - value: crêpe
        label: Crêpe
      - value: galette
        label: Galette
      - value: crumpet
        label: Crumpet
      - value: not_in_list
        label: Not in List
```

Would then be publicly queryable via http://localhost:5000/api/3/action/field_list?dataset=dataset (or similar)

```

{
   "scheming_version": 2,
   "dataset_type": "dataset",
   "about": "Ready for production dataset schema",
   "about_url": "http://www.example.com",
   "dataset_fields": [
      {
         "field_name": "foobar",
         "label": "Foo bar!",
         "form_placeholder": "Insert metasyntactic variable here!",
         "required": true
      },
      {
         "field_name": "pancake_preference",
         "help_text": "Refer to https://en.wikipedia.org/wiki/List_of_pancakes",
         "label": "Which Is the",
         "required": true,
         "preset": "select",
         "choices": [
            {
               "value": "crêpe",
               "label": "Crêpe"
            },
            {
               "value": "galette",
               "label": "Galette"
            },
            {
               "value": "crumpet",
               "label": "Crumpet"
            },
            {
               "value": "not_in_list",
               "label": "Not in List"
            }
         ]
      }
   ]
}
```

As someone who's not a CKAN developer I've implemented this in a truly brittle fashion locally with `pyyaml` because of failing to understand how the object model is working in CKAN. I'd be happy to open a PR doing this the right way or take any guidance on how to get something like this together using what's already available.

(p.s. Thanks for writing such an excellent plugin!)
