### ISSUE TITLE
Why can't I store boolean values?

### ISSUE THREAD

**Issue by roc** [ckan/ckanext-scheming#344]
My `ckan_dataset.yaml`

```
  - field_name: mandated
    label: Nationally Mandated
    required: true
    preset: select
    choices:
      - value: false
        label: "No"
      - value: true
        label: "Yes"
    validators: boolean_validator
```

How it looks in the CKAN form
<img width="1006" alt="Capture d’écran 2022-09-16 à 10 54 15" src="https://user-images.githubusercontent.com/120181/190598601-6caabebc-5ddd-4755-8ae7-e4330b95488b.png">

How it gets stored in the API
<img width="441" alt="Capture d’écran 2022-09-16 à 10 51 51" src="https://user-images.githubusercontent.com/120181/190598112-51d29510-d7ae-4aab-967a-c9d3603c0589.png">

### WHY? 

What's happening here? Is the boolean validator causing it to be set as a string "true" or "false"?

To get around this I've made a horrible hack to our select preset form and assigned it in the case where we have a ckan-scheming option that sets boolean values:

https://github.com/Marvell-Consulting/ckanext-scheming/commit/e7d050aa8abf82e2a3981ba927009eb22cb18c22#diff-eb6d8b864cdb6ac8796aa9745b925510d8f56c8d9b5b0ef29fa2a9965948b172

There must be a better way! What am I missing?!
