### ISSUE TITLE
Applying multiple schemas not working as expected

### ISSUE THREAD

**Issue by thorge** [ckan/ckanext-scheming#395]
I encountered an issue while attempting to integrate the scheming extension with an existing one. When declaring multiple dataset schemas using the `scheming.dataset_schemas` configuration option, only the last schema is applied. Unfortunately, the preceding schemas do not seem to be recognized or applied as expected. I'm curious if anyone else has experienced a similar problem. It's also plausible that the interference of my pre-existing extension might be contributing to this behavior. Any insights or guidance would be greatly appreciated.

**Steps to Reproduce:**
1. Create a simple test dataset schema `my_schema.yaml` with a single field.
  ```
  scheming_version: 2
  dataset_type: dataset
  about: Test Schema
  about_url: https://example.com
  
  dataset_fields:
  
    - field_name: test_field
      label: Test Field     
   ```
2. Declare multiple schemas in the configuration, as shown below:
   ```
   scheming.dataset_schemas = ckanext.scheming:ckan_dataset.yaml
                              ckanext.my_plugin:my_schema.yaml
   ```

**Expected Behavior:**
The dataset form should contain fields for all declared schemas..

**Actual Behavior:**
Only the fields from the last declared schema (`ckanext.my_plugin:my_schema.yaml`) are applied, and the previous schemas are ignored.

**Environment:**
- CKAN Version: 2.10.3
- ckanext-scheming Version: tried both, 3.0.0 and master
- Python Version: 3.8.10
- Operating System: 20.04
