### ISSUE TITLE
How to make some fields be hidden in the form view but displayed when viewing the dataset, especially for the id and name fields

### ISSUE THREAD

**Issue by fpichardom** [ckan/ckanext-scheming#433]
For my CKAN instance, I wanted the values for the fields `id` and `name` to be equal, so I have followed the path suggested in (https://github.com/ckan/ckan/discussions/8091). It works properly, but the issue I have is that now I want the `id` and `name` values to be displayed when viewing the dataset in the additional info table.

My presets are defined as:

```
- preset_name: biodigiknow_dataset_id
  values:
    create_validators: biodigiknow_validate_generate_uuid unicode_safe name_validator package_id_does_not_exist
    field_name: id
    form_snippet: null
    display_snippet: text.html

- preset_name: biodigiknow_dataset_name
  values:
    field_name: name
    form_snippet: null
    display_snippet: text.html
    validators: if_empty_same_as(id) not_empty unicode_safe biodigiknow_validate_generate_uuid
```

I have tried to put in my custom schema:

```
- field_name: id
  preset: biodigiknow_dataset_id
  label: ID

- field_name: name
  preset: biodigiknow_dataset_name
```

or

```
- preset: biodigiknow_dataset_id
- preset: biodigiknow_dataset_name
```

Neither of the options shows the values in the table after creation. Is it possible to do what I want, or is it just more complex than only modifying the custom forms yaml files using ckanext-scheming.
