### ISSUE TITLE
output_validators not effecting package_extras not in database

### ISSUE THREAD

**Issue by mackeynichols** [ckan/ckanext-scheming#443]
### CKAN Version
2.10.8

### Describe the Bug
When a field in the `package_extra` is not populated, `output_validator`s won't run on them.

### Replicating the bug

**Input**:
Call `<our_ckan>/api/3/action/package_show?id=id123` with the following body
 
- package `id123` doesnt have a value for "collection_method" in the package_extra database table
- package `id123` is of `dataset_type: "dataset"`
- 
**Expected Output**:
- "collection_method" field is shown as collection_method: null

**Actual Output**:
- "collection_method" field is not shown in  package_show response

### Configurations

I am using this YAML to configure scheming:

```
scheming_version: 2
dataset_type: dataset
about: A reimplementation of the default CKAN dataset schema
about_url: http://github.com/ckan/ckanext-scheming

dataset_fields:
  - field_name: title
    label: Title
    required: true

  - field_name: url
    label: URL
    preset: dataset_slug
    form_placeholder: eg. my-dataset
    required: true

  - field_name: collection_method
    label: Collection Method
    output_validators: default_to_none

resource_fields: 
  - field_name: title
    label: Title
    required: true

  - field_name: url
    label: URL
    preset: dataset_slug
    form_placeholder: eg. my-dataset
    required: true

```

It references this custom validator:

```
def default_to_none(value):
    if value:
        return value
    else:
        return None
```

I have been refreshing the SOLR index before and after making the `package_show` call.
